### PR TITLE
Fix backport issue in RHEL9.5

### PR DESCRIPTION
**Pull request by cyqsimon**
Similar to #29. It happened yet again for RHEL9.5.

### CODE REVIEW

**Comment by chrBrd** [comment]
Patches like this shouldn't be going into upstream IMO.

As mentioned in your first PR there aren't too many instances of conditional compilation. _Yet_. This PR and the other would add two.

I'm the maintainer for this for openSUSE distros where I have to deal with backports breaking things. If I upstreamed those patches that'd be yet more conditional compilation code. If you multiply this out for every somewhat popular distro then this repo would eventually become a mess.

Patching backport issues is really a distro maintainer's responsibility.

**Comment by cyqsimon** [comment]
@chrBrd Yeah it becomes more reasonable the more I think about it. I'll go submit these as source patches for  KyleGospo/gasket-dkms I suppose.

**Comment by chrBrd** [comment]
Good call! 

Apologies if my comment came off a bit blunt.

**Comment by cyqsimon** [comment]
> Apologies if my comment came off a bit blunt.

No worries, no offence taken 👌

**Pull request closed without merging**
